[package]
name = "u8bits"
version = "0.1.0"
authors = ["Robert Hennig <robert@freylax.de>"]
edition = "2018"

[dependencies]
paste = "0.1"
enum-primitive-derive = "0.1"

[dependencies.num-traits]
version = "0.2"
default-features = false
